name: 'Get and Cache Dependecies'
description: 'get and use deps'
inputs: 
  caching: 
    description: 'whther to cache or not'
    required: false
    default: 'true'
  someinput: 
    description: 'my input'
    required: true
    default: 'welcome'
    
runs:
  using: 'composite'
  steps:
    - name: print my input
      run: echo "${{ inputs.someinput }}"
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash